server:
  port: 9090
  servlet:
    context-path: /scheduler-financial-transfer

spring:
  application:
    name: SchedulerFinancialTransfer
  jpa:
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  rabbitmq:
    password: guest
    username: guest


rabbit-mq:
  scheduler-new:
    queue: scheduler-new-financial-transfer-queue
    exchange: scheduler-new-financial-transfer-exchange
    routing-key: scheduler-new-financial-transfer-routing-key
  scheduler-success:
    queue: scheduler-success-financial-transfer-queue
    exchange: scheduler-success-financial-transfer-exchange
    routing-key: scheduler-success-financial-transfer-routing-key
  scheduler-fail:
    queue: scheduler-fail-financial-transfer-queue
    exchange: scheduler-fail-financial-transfer-exchange
    routing-key: scheduler-fail-financial-transfer-routing-key

logging:
  level:
    com.scheduler_financial_transfer.code_interview: debug